const fs = require('fs');
let c = fs.readFileSync('src/pages/UserProfile.jsx', 'utf8');

c = c.replace(/const VISITOR_HISTORY = \[\s+([\s\S]*?)\];/, `const VISITOR_HISTORY = [
  { name: 'Suresh Kumar', number: '+91 9988776655', relation: 'Father', address: 'H.No 12, Ram Nagar, Aligarh, UP', purpose: 'Casual Visit', timeIn: '10:00 AM', timeOut: '05:00 PM', date: '2025-06-25', idProof: 'Aadhar: 1234 5678' },
  { name: 'Ramesh Singh',  number: '+91 9811223344', relation: 'Uncle',  address: '44, Karol Bagh, Delhi', purpose: 'Dropping luggage', timeIn: '08:30 AM', timeOut: '09:15 AM', date: '2025-05-12', idProof: 'DL: DL142011' },
  { name: 'Anita Kumar',   number: '+91 9988776644', relation: 'Mother', address: 'H.No 12, Ram Nagar, Aligarh, UP', purpose: 'Medical checkup', timeIn: '11:00 AM', timeOut: '06:30 PM', date: '2025-04-05', idProof: 'PAN: ABCDE1234F' },
  { name: 'Suresh Kumar', number: '+91 9988776655', relation: 'Father', address: 'H.No 12, Ram Nagar, Aligarh, UP', purpose: 'Bringing food', timeIn: '01:00 PM', timeOut: '02:00 PM', date: '2025-07-10', idProof: 'Aadhar: 1234 5678' },
];`);

c = c.replace(/function VisitorHistoryView\(\{\s*user,\s*onBack\s*\}\) \{[\s\S]*?return \([\s\S]*?\);\n\}/, `function VisitorHistoryView({ user, onBack }) {
  const [selectedVisitor, setSelectedVisitor] = useState(null);

  if (selectedVisitor) {
    const visits = VISITOR_HISTORY.filter(v => v.name === selectedVisitor.name).sort((a, b) => new Date(b.date) - new Date(a.date));
    return (
      <>
        <Header title={selectedVisitor.name} onBack={() => setSelectedVisitor(null)} center={false} />
        <div style={{ padding: 16 }}>
          <div style={{ marginBottom: 16, background: 'white', padding: 16, borderRadius: 12, border: '1px solid #e2e8f0' }}>
            <p style={{ fontSize: 13, color: '#64748b', margin: '0 0 4px' }}>Relation: <span style={{ color: '#0f172a', fontWeight: 600 }}>{selectedVisitor.relation}</span></p>
            <p style={{ fontSize: 13, color: '#64748b', margin: '0 0 4px' }}>Phone: <span style={{ color: '#0f172a', fontWeight: 600 }}>{selectedVisitor.number}</span></p>
            <p style={{ fontSize: 13, color: '#64748b', margin: 0 }}>ID Proof: <span style={{ color: '#0f172a', fontWeight: 600 }}>{selectedVisitor.idProof || 'N/A'}</span></p>
          </div>
          <p style={{ fontSize: 14, fontWeight: 700, color: '#334155', marginBottom: 12 }}>Past Visits</p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {visits.map((v, i) => (
              <div key={i} style={{ background: 'white', borderRadius: 12, border: '1px solid #e2e8f0', padding: 16 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 12, borderBottom: '1px solid #f1f5f9', paddingBottom: 12 }}>
                  <p style={{ fontSize: 14, fontWeight: 700, color: '#0f172a', margin: 0 }}>{new Date(v.date).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}</p>
                  <span style={{ fontSize: 12, fontWeight: 600, color: '#64748b' }}>{v.timeIn} - {v.timeOut}</span>
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                  <div style={{ display: 'flex', gap: 8 }}><span className="material-symbols-outlined" style={{ fontSize: 18, color: cyan }}>info</span><span style={{ fontSize: 13, color: '#475569' }}>{v.purpose}</span></div>
                  <div style={{ display: 'flex', gap: 8 }}><span className="material-symbols-outlined" style={{ fontSize: 18, color: cyan }}>location_on</span><span style={{ fontSize: 13, color: '#475569' }}>{v.address}</span></div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </>
    );
  }

  const grouped = VISITOR_HISTORY.reduce((acc, v) => {
    if (!acc[v.name]) acc[v.name] = { ...v, count: 0 };
    acc[v.name].count += 1;
    return acc;
  }, {});
  const uniqueVisitors = Object.values(grouped);

  return (
    <>
      <Header title="Visitor History" onBack={onBack} center={false} />
      <div style={{ padding: 16 }}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {uniqueVisitors.map((v, i) => (
            <div key={i} onClick={() => setSelectedVisitor(v)} style={{ background: 'white', borderRadius: 12, border: '1px solid #e2e8f0', padding: 16, cursor: 'pointer', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div>
                <p style={{ fontWeight: 700, fontSize: 16, color: '#0f172a', margin: '0 0 2px' }}>{v.name}</p>
                <p style={{ fontSize: 13, color: '#64748b', margin: 0 }}>{v.relation} · {v.number}</p>
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                <span style={{ background: '#ecfeff', color: cyan, fontSize: 12, fontWeight: 700, padding: '4px 10px', borderRadius: 20 }}>{v.count} Visit{v.count > 1 ? 's' : ''}</span>
                <span className="material-symbols-outlined" style={{ color: '#cbd5e1', fontSize: 20 }}>chevron_right</span>
              </div>
            </div>
          ))}
        </div>
      </div>
    </>
  );
}`);

c = c.replace('function Header({ title, onBack, action, center = true, dark = false }) {\n  return (\n    <div style={{ display: \'flex\', alignItems: \'center\', padding: \'16px 20px\', background: dark ? cyan : \'white\', borderBottom: dark ? \'none\' : \'1px solid #e2e8f0\', position: \'sticky\', top: 0, zIndex: 50 }}>', 'function Header({ title, onBack, action, center = true, dark = false, containerStyle = {} }) {\n  return (\n    <div style={{ display: \'flex\', alignItems: \'center\', padding: \'16px 20px\', background: dark ? cyan : \'white\', borderBottom: dark ? \'none\' : \'1px solid #e2e8f0\', position: \'sticky\', top: 0, zIndex: 50, ...containerStyle }}>');

c = c.replace('function Header({ title, onBack, action, center = true, dark = false }) {\r\n  return (\r\n    <div style={{ display: \'flex\', alignItems: \'center\', padding: \'16px 20px\', background: dark ? cyan : \'white\', borderBottom: dark ? \'none\' : \'1px solid #e2e8f0\', position: \'sticky\', top: 0, zIndex: 50 }}>', 'function Header({ title, onBack, action, center = true, dark = false, containerStyle = {} }) {\r\n  return (\r\n    <div style={{ display: \'flex\', alignItems: \'center\', padding: \'16px 20px\', background: dark ? cyan : \'white\', borderBottom: dark ? \'none\' : \'1px solid #e2e8f0\', position: \'sticky\', top: 0, zIndex: 50, ...containerStyle }}>');

c = c.replace('  return (\n    <>\n      <Header title="User Details" onBack={onBack} center={true} dark={true} action={', '  return (\n    <>\n      <div style={{ position: \'sticky\', top: 0, zIndex: 60 }}>\n        {profile.type === \'notice_period\' && profile.pending > 0 && (\n          <div style={{ background: \'#ef4444\', color: \'white\', padding: \'10px 16px\', display: \'flex\', justifyContent: \'center\', alignItems: \'center\', gap: 8 }}>\n            <span className="material-symbols-outlined" style={{ fontSize: 18 }}>warning</span>\n            <span style={{ fontSize: 13, fontWeight: 700 }}>Notice Period: ₹{profile.pending.toLocaleString()} Pending</span>\n          </div>\n        )}\n        <Header title="User Details" onBack={onBack} center={true} dark={true} containerStyle={{ position: \'relative\', zIndex: 50 }} action={');

c = c.replace('  return (\r\n    <>\r\n      <Header title="User Details" onBack={onBack} center={true} dark={true} action={', '  return (\r\n    <>\r\n      <div style={{ position: \'sticky\', top: 0, zIndex: 60 }}>\r\n        {profile.type === \'notice_period\' && profile.pending > 0 && (\r\n          <div style={{ background: \'#ef4444\', color: \'white\', padding: \'10px 16px\', display: \'flex\', justifyContent: \'center\', alignItems: \'center\', gap: 8 }}>\r\n            <span className="material-symbols-outlined" style={{ fontSize: 18 }}>warning</span>\r\n            <span style={{ fontSize: 13, fontWeight: 700 }}>Notice Period: ₹{profile.pending.toLocaleString()} Pending</span>\r\n          </div>\r\n        )}\r\n        <Header title="User Details" onBack={onBack} center={true} dark={true} containerStyle={{ position: \'relative\', zIndex: 50 }} action={');

c = c.replace('      }/>\n\n      <div style={{ background: cyan, padding: \'0 16', '      }/>\n      </div>\n\n      <div style={{ background: cyan, padding: \'0 16');

c = c.replace('      }/>\r\n\r\n      <div style={{ background: cyan, padding: \'0 16', '      }/>\r\n      </div>\r\n\r\n      <div style={{ background: cyan, padding: \'0 16');


c = c.replace('{profile.type === \'upcoming\' && (\n          <Accordion title="Token Amount" icon="payments" defaultOpen={false}>\n            <InfoRow label="Amount" value={`₹ ${token.toLocaleString()}`} />\n            <InfoRow label="Received by" value="Manager" last />\n          </Accordion>\n        )}', '{profile.type === \'upcoming\' && (\n          <>\n            <Accordion title="Token Amount" icon="payments" defaultOpen={false}>\n              <InfoRow label="Amount" value={`₹ ${token.toLocaleString()}`} />\n              <InfoRow label="Received by" value="Manager" last />\n            </Accordion>\n            <Accordion title="Late Fees (Token Expired Fine)" icon="money_off" defaultOpen={false}>\n              <InfoRow label="Paid To" value="Owner" />\n              <InfoRow label="Paid By" value={profile.name} />\n              <InfoRow label="Payment Method" value="UPI" />\n              <InfoRow label="Room Rent" value={`₹ ${profile.rent.toLocaleString()}`} last />\n            </Accordion>\n          </>\n        )}');

c = c.replace('{profile.type === \'upcoming\' && (\r\n          <Accordion title="Token Amount" icon="payments" defaultOpen={false}>\r\n            <InfoRow label="Amount" value={`₹ ${token.toLocaleString()}`} />\r\n            <InfoRow label="Received by" value="Manager" last />\r\n          </Accordion>\r\n        )}', '{profile.type === \'upcoming\' && (\r\n          <>\r\n            <Accordion title="Token Amount" icon="payments" defaultOpen={false}>\r\n              <InfoRow label="Amount" value={`₹ ${token.toLocaleString()}`} />\r\n              <InfoRow label="Received by" value="Manager" last />\r\n            </Accordion>\r\n            <Accordion title="Late Fees (Token Expired Fine)" icon="money_off" defaultOpen={false}>\r\n              <InfoRow label="Paid To" value="Owner" />\r\n              <InfoRow label="Paid By" value={profile.name} />\r\n              <InfoRow label="Payment Method" value="UPI" />\r\n              <InfoRow label="Room Rent" value={`₹ ${profile.rent.toLocaleString()}`} last />\r\n            </Accordion>\r\n          </>\r\n        )}');


c = c.replace('const STUDENT_COOK_DATA = {\n  mealLog: [\n    { date: \'2026-07-11\', breakfast: true,  lunch: true,  dinner: false, extraPlates: 0,  tiffin: false },\n    { date: \'2026-07-10\', breakfast: true,  lunch: true,  dinner: true,  extraPlates: 2,  tiffin: false },\n    { date: \'2026-07-09\', breakfast: false, lunch: true,  dinner: true,  extraPlates: 0,  tiffin: true  },\n    { date: \'2026-07-08\', breakfast: true,  lunch: false, dinner: true,  extraPlates: 0,  tiffin: false },\n    { date: \'2026-07-07\', breakfast: true,  lunch: true,  dinner: true,  extraPlates: 1,  tiffin: false },\n    { date: \'2026-07-06\', breakfast: false, lunch: true,  dinner: false, extraPlates: 0,  tiffin: true  },\n    { date: \'2026-07-05\', breakfast: true,  lunch: true,  dinner: true,  extraPlates: 0,  tiffin: false },\n  ],', 'const STUDENT_COOK_DATA = {\n  mealLog: [\n    { date: \'2026-07-11\', breakfast: true,  lunch: true,  dinner: false, extraPlates: 0,  tiffin: false, usersAsked: 45, storedFood: true,  tiffinItems: [] },\n    { date: \'2026-07-10\', breakfast: true,  lunch: true,  dinner: true,  extraPlates: 2,  tiffin: false, usersAsked: 42, storedFood: false, tiffinItems: [] },\n    { date: \'2026-07-09\', breakfast: false, lunch: true,  dinner: true,  extraPlates: 0,  tiffin: true,  usersAsked: 50, storedFood: false, tiffinItems: [\'Roti\', \'Sabzi\', \'Salad\'] },\n    { date: \'2026-07-08\', breakfast: true,  lunch: false, dinner: true,  extraPlates: 0,  tiffin: false, usersAsked: 38, storedFood: true,  tiffinItems: [] },\n    { date: \'2026-07-07\', breakfast: true,  lunch: true,  dinner: true,  extraPlates: 1,  tiffin: false, usersAsked: 40, storedFood: false, tiffinItems: [] },\n    { date: \'2026-07-06\', breakfast: false, lunch: true,  dinner: false, extraPlates: 0,  tiffin: true,  usersAsked: 48, storedFood: true,  tiffinItems: [\'Pulao\', \'Raita\'] },\n    { date: \'2026-07-05\', breakfast: true,  lunch: true,  dinner: true,  extraPlates: 0,  tiffin: false, usersAsked: 41, storedFood: false, tiffinItems: [] },\n  ],');

c = c.replace('const STUDENT_COOK_DATA = {\r\n  mealLog: [\r\n    { date: \'2026-07-11\', breakfast: true,  lunch: true,  dinner: false, extraPlates: 0,  tiffin: false },\r\n    { date: \'2026-07-10\', breakfast: true,  lunch: true,  dinner: true,  extraPlates: 2,  tiffin: false },\r\n    { date: \'2026-07-09\', breakfast: false, lunch: true,  dinner: true,  extraPlates: 0,  tiffin: true  },\r\n    { date: \'2026-07-08\', breakfast: true,  lunch: false, dinner: true,  extraPlates: 0,  tiffin: false },\r\n    { date: \'2026-07-07\', breakfast: true,  lunch: true,  dinner: true,  extraPlates: 1,  tiffin: false },\r\n    { date: \'2026-07-06\', breakfast: false, lunch: true,  dinner: false, extraPlates: 0,  tiffin: true  },\r\n    { date: \'2026-07-05\', breakfast: true,  lunch: true,  dinner: true,  extraPlates: 0,  tiffin: false },\r\n  ],', 'const STUDENT_COOK_DATA = {\r\n  mealLog: [\r\n    { date: \'2026-07-11\', breakfast: true,  lunch: true,  dinner: false, extraPlates: 0,  tiffin: false, usersAsked: 45, storedFood: true,  tiffinItems: [] },\r\n    { date: \'2026-07-10\', breakfast: true,  lunch: true,  dinner: true,  extraPlates: 2,  tiffin: false, usersAsked: 42, storedFood: false, tiffinItems: [] },\r\n    { date: \'2026-07-09\', breakfast: false, lunch: true,  dinner: true,  extraPlates: 0,  tiffin: true,  usersAsked: 50, storedFood: false, tiffinItems: [\'Roti\', \'Sabzi\', \'Salad\'] },\r\n    { date: \'2026-07-08\', breakfast: true,  lunch: false, dinner: true,  extraPlates: 0,  tiffin: false, usersAsked: 38, storedFood: true,  tiffinItems: [] },\r\n    { date: \'2026-07-07\', breakfast: true,  lunch: true,  dinner: true,  extraPlates: 1,  tiffin: false, usersAsked: 40, storedFood: false, tiffinItems: [] },\r\n    { date: \'2026-07-06\', breakfast: false, lunch: true,  dinner: false, extraPlates: 0,  tiffin: true,  usersAsked: 48, storedFood: true,  tiffinItems: [\'Pulao\', \'Raita\'] },\r\n    { date: \'2026-07-05\', breakfast: true,  lunch: true,  dinner: true,  extraPlates: 0,  tiffin: false, usersAsked: 41, storedFood: false, tiffinItems: [] },\r\n  ],');


c = c.replace('              <div style={{ display: \'flex\', gap: 8 }}>\n                {([[\'Breakfast\', d.breakfast], [\'Lunch\', d.lunch], [\'Dinner\', d.dinner]] as const).map(([label, had]) => (\n                  <span key={label} style={{ flex: 1, textAlign: \'center\', padding: \'5px 4px\', borderRadius: 8, background: had ? \'#ecfeff\' : \'#f1f5f9\', color: had ? cyan : \'#94a3b8\', fontSize: 12, fontWeight: 700 }}>\n                    {had ? \'✓\' : \'✗\'} {label}\n                  </span>\n                ))}\n              </div>\n            </div>', '              <div style={{ display: \'flex\', gap: 8, marginBottom: 12 }}>\n                {([[\'Breakfast\', d.breakfast], [\'Lunch\', d.lunch], [\'Dinner\', d.dinner]] as const).map(([label, had]) => (\n                  <span key={label} style={{ flex: 1, textAlign: \'center\', padding: \'5px 4px\', borderRadius: 8, background: had ? \'#ecfeff\' : \'#f1f5f9\', color: had ? cyan : \'#94a3b8\', fontSize: 12, fontWeight: 700 }}>\n                    {had ? \'✓\' : \'✗\'} {label}\n                  </span>\n                ))}\n              </div>\n              <div style={{ background: \'#f8fafc\', borderRadius: 8, padding: 10, display: \'flex\', flexDirection: \'column\', gap: 6 }}>\n                <div style={{ display: \'flex\', alignItems: \'center\', gap: 6 }}>\n                  <span className="material-symbols-outlined" style={{ fontSize: 16, color: \'#64748b\' }}>forum</span>\n                  <span style={{ fontSize: 12, color: \'#475569\', fontWeight: 600 }}>{d.usersAsked} users asked</span>\n                </div>\n                {d.storedFood && (\n                  <div style={{ display: \'flex\', alignItems: \'center\', gap: 6 }}>\n                    <span className="material-symbols-outlined" style={{ fontSize: 16, color: \'#f59e0b\' }}>inventory_2</span>\n                    <span style={{ fontSize: 12, color: \'#475569\', fontWeight: 600 }}>Stored late food</span>\n                  </div>\n                )}\n                {d.tiffin && d.tiffinItems?.length > 0 && (\n                  <div style={{ display: \'flex\', alignItems: \'center\', gap: 6 }}>\n                    <span className="material-symbols-outlined" style={{ fontSize: 16, color: \'#16a34a\' }}>takeout_dining</span>\n                    <span style={{ fontSize: 12, color: \'#475569\', fontWeight: 600 }}>Tiffin: {d.tiffinItems.join(\', \')}</span>\n                  </div>\n                )}\n              </div>\n            </div>');

c = c.replace('              <div style={{ display: \'flex\', gap: 8 }}>\r\n                {([[\'Breakfast\', d.breakfast], [\'Lunch\', d.lunch], [\'Dinner\', d.dinner]] as const).map(([label, had]) => (\r\n                  <span key={label} style={{ flex: 1, textAlign: \'center\', padding: \'5px 4px\', borderRadius: 8, background: had ? \'#ecfeff\' : \'#f1f5f9\', color: had ? cyan : \'#94a3b8\', fontSize: 12, fontWeight: 700 }}>\r\n                    {had ? \'✓\' : \'✗\'} {label}\r\n                  </span>\r\n                ))}\r\n              </div>\r\n            </div>', '              <div style={{ display: \'flex\', gap: 8, marginBottom: 12 }}>\r\n                {([[\'Breakfast\', d.breakfast], [\'Lunch\', d.lunch], [\'Dinner\', d.dinner]] as const).map(([label, had]) => (\r\n                  <span key={label} style={{ flex: 1, textAlign: \'center\', padding: \'5px 4px\', borderRadius: 8, background: had ? \'#ecfeff\' : \'#f1f5f9\', color: had ? cyan : \'#94a3b8\', fontSize: 12, fontWeight: 700 }}>\r\n                    {had ? \'✓\' : \'✗\'} {label}\r\n                  </span>\r\n                ))}\r\n              </div>\r\n              <div style={{ background: \'#f8fafc\', borderRadius: 8, padding: 10, display: \'flex\', flexDirection: \'column\', gap: 6 }}>\r\n                <div style={{ display: \'flex\', alignItems: \'center\', gap: 6 }}>\r\n                  <span className="material-symbols-outlined" style={{ fontSize: 16, color: \'#64748b\' }}>forum</span>\r\n                  <span style={{ fontSize: 12, color: \'#475569\', fontWeight: 600 }}>{d.usersAsked} users asked</span>\r\n                </div>\r\n                {d.storedFood && (\r\n                  <div style={{ display: \'flex\', alignItems: \'center\', gap: 6 }}>\r\n                    <span className="material-symbols-outlined" style={{ fontSize: 16, color: \'#f59e0b\' }}>inventory_2</span>\r\n                    <span style={{ fontSize: 12, color: \'#475569\', fontWeight: 600 }}>Stored late food</span>\r\n                  </div>\r\n                )}\r\n                {d.tiffin && d.tiffinItems?.length > 0 && (\r\n                  <div style={{ display: \'flex\', alignItems: \'center\', gap: 6 }}>\r\n                    <span className="material-symbols-outlined" style={{ fontSize: 16, color: \'#16a34a\' }}>takeout_dining</span>\r\n                    <span style={{ fontSize: 12, color: \'#475569\', fontWeight: 600 }}>Tiffin: {d.tiffinItems.join(\', \')}</span>\r\n                  </div>\r\n                )}\r\n              </div>\r\n            </div>');

c = c.replace('              <div style={{ display: \'flex\', gap: 8 }}>\n                {([[\'Breakfast\', d.breakfast], [\'Lunch\', d.lunch], [\'Dinner\', d.dinner]]).map(([label, had]) => (\n                  <span key={label} style={{ flex: 1, textAlign: \'center\', padding: \'5px 4px\', borderRadius: 8, background: had ? \'#ecfeff\' : \'#f1f5f9\', color: had ? cyan : \'#94a3b8\', fontSize: 12, fontWeight: 700 }}>\n                    {had ? \'✓\' : \'✗\'} {label}\n                  </span>\n                ))}\n              </div>\n            </div>', '              <div style={{ display: \'flex\', gap: 8, marginBottom: 12 }}>\n                {([[\'Breakfast\', d.breakfast], [\'Lunch\', d.lunch], [\'Dinner\', d.dinner]]).map(([label, had]) => (\n                  <span key={label} style={{ flex: 1, textAlign: \'center\', padding: \'5px 4px\', borderRadius: 8, background: had ? \'#ecfeff\' : \'#f1f5f9\', color: had ? cyan : \'#94a3b8\', fontSize: 12, fontWeight: 700 }}>\n                    {had ? \'✓\' : \'✗\'} {label}\n                  </span>\n                ))}\n              </div>\n              <div style={{ background: \'#f8fafc\', borderRadius: 8, padding: 10, display: \'flex\', flexDirection: \'column\', gap: 6 }}>\n                <div style={{ display: \'flex\', alignItems: \'center\', gap: 6 }}>\n                  <span className="material-symbols-outlined" style={{ fontSize: 16, color: \'#64748b\' }}>forum</span>\n                  <span style={{ fontSize: 12, color: \'#475569\', fontWeight: 600 }}>{d.usersAsked} users asked</span>\n                </div>\n                {d.storedFood && (\n                  <div style={{ display: \'flex\', alignItems: \'center\', gap: 6 }}>\n                    <span className="material-symbols-outlined" style={{ fontSize: 16, color: \'#f59e0b\' }}>inventory_2</span>\n                    <span style={{ fontSize: 12, color: \'#475569\', fontWeight: 600 }}>Stored late food</span>\n                  </div>\n                )}\n                {d.tiffin && d.tiffinItems?.length > 0 && (\n                  <div style={{ display: \'flex\', alignItems: \'center\', gap: 6 }}>\n                    <span className="material-symbols-outlined" style={{ fontSize: 16, color: \'#16a34a\' }}>takeout_dining</span>\n                    <span style={{ fontSize: 12, color: \'#475569\', fontWeight: 600 }}>Tiffin: {d.tiffinItems.join(\', \')}</span>\n                  </div>\n                )}\n              </div>\n            </div>');

c = c.replace('              <div style={{ display: \'flex\', gap: 8 }}>\r\n                {([[\'Breakfast\', d.breakfast], [\'Lunch\', d.lunch], [\'Dinner\', d.dinner]]).map(([label, had]) => (\r\n                  <span key={label} style={{ flex: 1, textAlign: \'center\', padding: \'5px 4px\', borderRadius: 8, background: had ? \'#ecfeff\' : \'#f1f5f9\', color: had ? cyan : \'#94a3b8\', fontSize: 12, fontWeight: 700 }}>\r\n                    {had ? \'✓\' : \'✗\'} {label}\r\n                  </span>\r\n                ))}\r\n              </div>\r\n            </div>', '              <div style={{ display: \'flex\', gap: 8, marginBottom: 12 }}>\r\n                {([[\'Breakfast\', d.breakfast], [\'Lunch\', d.lunch], [\'Dinner\', d.dinner]]).map(([label, had]) => (\r\n                  <span key={label} style={{ flex: 1, textAlign: \'center\', padding: \'5px 4px\', borderRadius: 8, background: had ? \'#ecfeff\' : \'#f1f5f9\', color: had ? cyan : \'#94a3b8\', fontSize: 12, fontWeight: 700 }}>\r\n                    {had ? \'✓\' : \'✗\'} {label}\r\n                  </span>\r\n                ))}\r\n              </div>\r\n              <div style={{ background: \'#f8fafc\', borderRadius: 8, padding: 10, display: \'flex\', flexDirection: \'column\', gap: 6 }}>\r\n                <div style={{ display: \'flex\', alignItems: \'center\', gap: 6 }}>\r\n                  <span className="material-symbols-outlined" style={{ fontSize: 16, color: \'#64748b\' }}>forum</span>\r\n                  <span style={{ fontSize: 12, color: \'#475569\', fontWeight: 600 }}>{d.usersAsked} users asked</span>\r\n                </div>\r\n                {d.storedFood && (\r\n                  <div style={{ display: \'flex\', alignItems: \'center\', gap: 6 }}>\r\n                    <span className="material-symbols-outlined" style={{ fontSize: 16, color: \'#f59e0b\' }}>inventory_2</span>\r\n                    <span style={{ fontSize: 12, color: \'#475569\', fontWeight: 600 }}>Stored late food</span>\r\n                  </div>\r\n                )}\r\n                {d.tiffin && d.tiffinItems?.length > 0 && (\r\n                  <div style={{ display: \'flex\', alignItems: \'center\', gap: 6 }}>\r\n                    <span className="material-symbols-outlined" style={{ fontSize: 16, color: \'#16a34a\' }}>takeout_dining</span>\r\n                    <span style={{ fontSize: 12, color: \'#475569\', fontWeight: 600 }}>Tiffin: {d.tiffinItems.join(\', \')}</span>\r\n                  </div>\r\n                )}\r\n              </div>\r\n            </div>');

c = c.replace('              <div style={{ display: \'flex\', gap: 8 }}>\n                {[[\'Breakfast\', d.breakfast], [\'Lunch\', d.lunch], [\'Dinner\', d.dinner]].map(([label, had]) => (\n                  <span key={label} style={{ flex: 1, textAlign: \'center\', padding: \'5px 4px\', borderRadius: 8, background: had ? \'#ecfeff\' : \'#f1f5f9\', color: had ? cyan : \'#94a3b8\', fontSize: 12, fontWeight: 700 }}>\n                    {had ? \'✓\' : \'✗\'} {label}\n                  </span>\n                ))}\n              </div>\n            </div>', '              <div style={{ display: \'flex\', gap: 8, marginBottom: 12 }}>\n                {[[\'Breakfast\', d.breakfast], [\'Lunch\', d.lunch], [\'Dinner\', d.dinner]].map(([label, had]) => (\n                  <span key={label} style={{ flex: 1, textAlign: \'center\', padding: \'5px 4px\', borderRadius: 8, background: had ? \'#ecfeff\' : \'#f1f5f9\', color: had ? cyan : \'#94a3b8\', fontSize: 12, fontWeight: 700 }}>\n                    {had ? \'✓\' : \'✗\'} {label}\n                  </span>\n                ))}\n              </div>\n              <div style={{ background: \'#f8fafc\', borderRadius: 8, padding: 10, display: \'flex\', flexDirection: \'column\', gap: 6 }}>\n                <div style={{ display: \'flex\', alignItems: \'center\', gap: 6 }}>\n                  <span className="material-symbols-outlined" style={{ fontSize: 16, color: \'#64748b\' }}>forum</span>\n                  <span style={{ fontSize: 12, color: \'#475569\', fontWeight: 600 }}>{d.usersAsked} users asked</span>\n                </div>\n                {d.storedFood && (\n                  <div style={{ display: \'flex\', alignItems: \'center\', gap: 6 }}>\n                    <span className="material-symbols-outlined" style={{ fontSize: 16, color: \'#f59e0b\' }}>inventory_2</span>\n                    <span style={{ fontSize: 12, color: \'#475569\', fontWeight: 600 }}>Stored late food</span>\n                  </div>\n                )}\n                {d.tiffin && d.tiffinItems?.length > 0 && (\n                  <div style={{ display: \'flex\', alignItems: \'center\', gap: 6 }}>\n                    <span className="material-symbols-outlined" style={{ fontSize: 16, color: \'#16a34a\' }}>takeout_dining</span>\n                    <span style={{ fontSize: 12, color: \'#475569\', fontWeight: 600 }}>Tiffin: {d.tiffinItems.join(\', \')}</span>\n                  </div>\n                )}\n              </div>\n            </div>');

c = c.replace('              <div style={{ display: \'flex\', gap: 8 }}>\r\n                {[[\'Breakfast\', d.breakfast], [\'Lunch\', d.lunch], [\'Dinner\', d.dinner]].map(([label, had]) => (\r\n                  <span key={label} style={{ flex: 1, textAlign: \'center\', padding: \'5px 4px\', borderRadius: 8, background: had ? \'#ecfeff\' : \'#f1f5f9\', color: had ? cyan : \'#94a3b8\', fontSize: 12, fontWeight: 700 }}>\r\n                    {had ? \'✓\' : \'✗\'} {label}\r\n                  </span>\r\n                ))}\r\n              </div>\r\n            </div>', '              <div style={{ display: \'flex\', gap: 8, marginBottom: 12 }}>\r\n                {[[\'Breakfast\', d.breakfast], [\'Lunch\', d.lunch], [\'Dinner\', d.dinner]].map(([label, had]) => (\r\n                  <span key={label} style={{ flex: 1, textAlign: \'center\', padding: \'5px 4px\', borderRadius: 8, background: had ? \'#ecfeff\' : \'#f1f5f9\', color: had ? cyan : \'#94a3b8\', fontSize: 12, fontWeight: 700 }}>\r\n                    {had ? \'✓\' : \'✗\'} {label}\r\n                  </span>\r\n                ))}\r\n              </div>\r\n              <div style={{ background: \'#f8fafc\', borderRadius: 8, padding: 10, display: \'flex\', flexDirection: \'column\', gap: 6 }}>\r\n                <div style={{ display: \'flex\', alignItems: \'center\', gap: 6 }}>\r\n                  <span className="material-symbols-outlined" style={{ fontSize: 16, color: \'#64748b\' }}>forum</span>\r\n                  <span style={{ fontSize: 12, color: \'#475569\', fontWeight: 600 }}>{d.usersAsked} users asked</span>\r\n                </div>\r\n                {d.storedFood && (\r\n                  <div style={{ display: \'flex\', alignItems: \'center\', gap: 6 }}>\r\n                    <span className="material-symbols-outlined" style={{ fontSize: 16, color: \'#f59e0b\' }}>inventory_2</span>\r\n                    <span style={{ fontSize: 12, color: \'#475569\', fontWeight: 600 }}>Stored late food</span>\r\n                  </div>\r\n                )}\r\n                {d.tiffin && d.tiffinItems?.length > 0 && (\r\n                  <div style={{ display: \'flex\', alignItems: \'center\', gap: 6 }}>\r\n                    <span className="material-symbols-outlined" style={{ fontSize: 16, color: \'#16a34a\' }}>takeout_dining</span>\r\n                    <span style={{ fontSize: 12, color: \'#475569\', fontWeight: 600 }}>Tiffin: {d.tiffinItems.join(\', \')}</span>\r\n                  </div>\r\n                )}\r\n              </div>\r\n            </div>');

fs.writeFileSync('src/pages/UserProfile.modified.jsx', c);
